services:
  utsuki-bot-net:
    image: utsuki-bot-net
    container_name: utsuki-bot-net
    restart: always
    environment:
      DISCORD_TOKEN_UTSUKI: ${DISCORD_TOKEN_UTSUKI}
      AI_ENDPOINT: ${AI_ENDPOINT}
      AI_TOKEN: ${AI_TOKEN}
      API_KEY_WEATHER: ${API_KEY_WEATHER}
      BOT_VERSION: ${BOT_VERSION}
      ARCHIVE_GUILD_IDS: ${ARCHIVE_GUILD_IDS:-}
    volumes:
      - ./JsonData:/app/JsonData
      - ./db:/app/db
